bbsnote/urls.py
from django.urls import path
from . import views

app_name = "bbsnote"

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:board_id>/', views.detail, name='detail'), 
    path('comment/create/<int:board_id>/', views.comment_create, name='comment_create'),
    path('board/create/', views.board_create, name='board_create'),
    path('board/modify/<int:board_id>/', views.board_modify, name='board_modify'),
    path('board/delete/<int:board_id>', views.board_delete, name='board_delete'),
    path('comment/modify/<int:comment_id>/', views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
]

common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from. import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from bbsnote import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bbsnote/', include('bbsnote.urls')),   # bbsnote.urls 을 포함시키다
    path('common/', include('common.urls')),   # common.urls 을 포함시키다
    path('', views.index, name='index'),
]

bbsnote/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Board(models.Model):  # 게시글 모델
    subject = models.CharField(max_length=200) # 문자열필드(CharField) 형태로 최대 길이 200자로 제한
    content = models.TextField() # 텍스트 필드
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True) # 날짜/시간 필드 / 객체가 처음 생성될 때 자동으로 현재 날짜/시간으로
    update_date = models.DateTimeField(auto_now=True) # 날짜/시간 필드 / 객체가 저장될 때마다 현재 날짜/시간으로 설정

    def __str__(self):
        return f'[{self.id}] {self.subject}' # Board를 불러올때, [id][제목] 형태로 객체를 출력

class Comment(models.Model): # 댓글 모델
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # like = models.IntegerField(blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-create_date']

    def __str__(self):
        return f'[{self.board.id}:{self.board.subject} ] {self.content}'

bbsnote/forms.py
from django import forms # 장고로부터 임포트
from bbsnote.models import Board, Comment

class BoardForm(forms.ModelForm): #모델폼을 상속받을게
    class Meta:
        model = Board
        fields = ['subject', 'content']
        # widgets = {
        #    'subject' : forms.TextInput(attrs={'class':'form-control'}),
        #    'content' : forms.Textarea(attrs={'class':'form-control','rows':10}),
        # }
        # labels = {
        #     'subject':'제목',
        #     'content':'내용',
        # }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글 내용'
        }        

bbsnote/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Board, Comment
from django.utils import timezone
from .forms import BoardForm, CommentForm 
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.
def profile(request):
    return redirect('myProfile.html')
def index(request):
    # 입력인자
    page = request.GET.get('page', 1) #페이지값이 있으면 가져오고 없으면 1로 초기화
    # 조회
    board_list = Board.objects.order_by('-create_date') # http://127.0.0.1:8000/bbsnote/ = create_date에서 -를 빼면 위에서부터 작성한 순서대로 나열됨 -를 추가하면 반대임
    # 페이징 처리
    paginator = Paginator(board_list, 3)
    page_obj = paginator.get_page(page) # 12번줄의 page를 여기로 불러온다
    context = {'board_list': page_obj}
    # return HttpResponse("bbsnote에 오신 것을 환영합니다")
    return render(request, 'bbsnote/board_list.html', context)  

def detail(request, board_id):
    board = Board.objects.get(id=board_id) # (id=board_id) = select * from bbsnote_Board wher id=5
    context = {'board': board}
    return render(request, 'bbsnote/board_detail.html', context)  

@login_required(login_url='common:login')
def comment_create(request, board_id):
    if request.method == 'POST':
        board = Board.objects.get(id=board_id)
    # comment = Comment(board=board, content=request.POST.get('content'), create_date=timezone.now())
    # comment.save()  # 20~21번 코드는 밑에 22번줄 코드와 같은 결과
        board.comment_set.create(content=request.POST.get('content'), create_date=timezone.now(), author=request.user)
    #   return redirect('bbsnote:detail', board_id=board.id)   bbsnote:detail 으로 리다이렉트 
    return redirect('bbsnote:detail', board_id=board_id)

@login_required(login_url='common:login')
def board_create(request):
    if request.method == 'POST':  #요청 리퀘스트 들어왔는데 포스트로 왔으면
        form = BoardForm(request.POST) #리퀘스트.포스트를 보드리폼에 넘겨줘
        if form.is_valid():  #만약에 폼의 값이 있으면
            board = form.save(commit=False) # 실행은 시키되 저장은 아직 = 오토커밋 시키지마 잠깐 기다려라
            # board.create_date = timezone.now()  #이것은 없어도 게시글 저장에는 문제 없다
            board.author = request.user
            board.save()
            return redirect('index') # 저장 잘되있으면 bbsnote:index' 가라
    else:
        form = BoardForm() # forms.py의 class BoardForm
    return render(request, 'bbsnote/board_form.html', {'form':form})

@login_required(login_url='common:login')
def board_modify(request, board_id):
    board = get_object_or_404(Board, pk=board_id)
    if request.user != board.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('bbsnote:detail', board_id=board.id) 
    if request.method == "POST":
        form = BoardForm(request.POST, instance=board)
        if form.is_valid():
            board = form.save(commit=False) # False 여서 완전이 아닌 임시저장
            board.author = request.user
            board.update_date = timezone.now()  # 수정일시 저장
            board.save()
            return redirect('bbsnote:detail', board_id=board.id)
    else:
        form = BoardForm(instance=board) 
    context = {'form': form}
    return render(request, 'bbsnote/board_form.html', context)

@login_required(login_url='common:login')
def board_delete(request, board_id):
    board = get_object_or_404(Board, pk=board_id)
    if request.user != board.author:     # 작성자와 수정자가 다르면 밑에 삭제 권한이 없습니다 뜨게끔
        messages.error(request, '삭제 권한이 없습니다')
        return redirect('bbsnote:detail', board_id=board.id)
    board.delete()
    return redirect('bbsnote:index')

@login_required(login_url='common:login')
def comment_modify(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, "수정 권한이 없습니다!")
        return redirect('bbsnote:detail', board_id=comment.board.id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.auahor = request.user
            comment.save()
            return redirect('bbsnote:detail', board_id=comment.board.id)
    else:
        form = CommentForm(instance=comment)
    context = {'comment':comment, 'form':form}
    return render(request, 'bbsnote/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '삭제 권한이 없습니다')
        return redirect('bbsnote:detail', board_id=comment.board.id)
    comment.delete()
    return redirect('bbsnote:detail', board_id=comment.board.id)   

templates/bbsnote/board_detail.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul>
            <li>{{ message.message }}</li>
        </ul>
        {% endfor %}
    </div>
    {% endif %}
    <h2 class="border-bottom py-2">{{ board.subject }}</h2>
    <div class="col-11"> <!-- 본문 -->
        <div class="card">  
            <div class="card-body">
                <div class="card-text">{{ board.content }}</div>
                <div class="d-flex justify-content-end">
                    {% if board.update_date %}
                    <div class="badge badge-light p-2 text-left mx-3">
                        <div class="mb-2">modified at</div>
                        <div>{{ board.update_date|date:'Y-m-d A H:i'  }}</div>
                    </div>
                    {% endif %}
                    <div class="badge badge-light p-2 text-left">
                        <div class="mb-2">{{ board.author.username }}</div>
                        <div>{{ board.create_date|date:'Y-m-d A H:i'  }}</div>
                    </div>
            </div>
            {% if request.user == board.author %}
            <div class="my-3">
                <a href="{% url 'bbsnote:board_modify' board.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'bbsnote:board_delete' board.id %}">삭제</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
<h6 class="border-bottom my-3 py-2">{{board.comment_set.count}}개의 댓글이 있습니다.</h6>
{% if board.comment_set.count > 0 %}
<div class="mt-3">
    {% for comment in board.comment_set.all %}
    <div class="comment py-2 text-muted">
        <span style="white-space: pre-line;">{{ comment.content }}</span>
        {% if request.user == comment.author %}
        <a href="{% url 'bbsnote:comment_modify' comment.id %}" class="small">수정</a>
        <a href="#" class="small delete" data-uri="{% url 'bbsnote:comment_delete' comment.id %}">삭제</a>
        {% endif %}
        <div class="d-flex justify-content-end">
            {% if comment.update_date %}
            <div class="badge badge-light p-2 text-left">
                <div class="mb-2">modified at</div>
                <div>{{ comment.update_date|date:'Y-m-d A H:i' }}</div>
            </div>
            {% endif %}
            <div class="badge badge-light p-2 text-left">
                <div class="mb-2">{{ comment.author.username }}</div>
                <div>{{ comment.create_date|date:'Y-m-d A H:i' }}</div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}
    <form action="{% url 'bbsnote:comment_create' board.id %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="3"></textarea>
        </div>
        <input type="submit" value="댓글달기" class="btn btn-primary">
    </form>
</div>
{% endblock %} 
{% block script %} 
<script type="text/javascript">  
    $(document).ready(function () { 
        $(".delete").on('click', function () {
            if (confirm("정말로 삭제하시겠습니까?")){  
                location.href = $(this).data('uri');   
            }  
        }); 
    }); 
</script> 
{% endblock %} 

templates/bbsnote/board_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">게시글 등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장</button>
    </form>
</div>
{% endblock %}

templates/bbsnote/board_list.html
{% extends 'base.html' %}
{% load bbsnote_filter %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="text-center thead-dark"> 
            <th></th>           
            <th style="width:50%">제목</th>
            <th>작성자</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if board_list %}
        {% for board in board_list %}
        <tr class="text-center">
            <td>{{ board_list.paginator.count|sub:board_list.start_index|sub:forloop.counter0|add:1 }}</td>
            <td class="text-left">
                <a href="{% url 'bbsnote:detail' board.id %}">
                    {{ board.subject }}
                    {% if board.comment_set.count > 0 %}
                    <span class="text-danger small ml-2">
                        [{{ board.comment_set.count }}]
                    </span>
                    {% endif %}
                </a>                
            </td>
            <td>{{board.author.username}}</td>            
            <td>{{ board.create_date|date:'Y-m-d A H:i' }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table> 
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if board_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ board_list.previous_page_number }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">  
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in board_list.paginator.page_range %}
        {% if page_number >= board_list.number|add:-5 and page_number <= board_list.number|add:5 %}
            {% if page_number == board_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %} 
        {% endfor %}
        <!-- 다음페이지 -->
        {% if board_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ board_list.next_page_number }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 --> 
    {% if user.is_authenticated %}
    <a href="{% url 'bbsnote:board_create' %}" class="btn btn-primary">등록</a>   
    {% endif %}
</div> 
<form id="searchForm" method="get" action="{% url 'bbsnote:index' %}">    
    <input type="hidden" id="page" name="page" value="{{ page }}">   <!-- -->  
</form>
{% endblock %}
{% block script %}

<script type='text/javascript'> 
$(document).ready(function(){ 
    $(".page-link").on('click', function() {    
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();  
    });     
});
</script>
{% endblock %}

templates/bbsnote/comment_form.html
{% extends 'base.html' %}
{% block content  %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control" name="content" id="content"
                rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}